### ISSUE TITLE
Front page of the network

### ISSUE THREAD

**Issue by evabl444** [LiUSemWeb/CEON#57]
Is it possible to do something with the front page of the network, i.e. w3id.org/CEON to have more information there, and not only the generated index of the modules?

**Comment by keski** [comment]
Updating the index file is very straightforward: simply make the changes in `index.hbs` in the project root. This file is used as a template in the generation of the index page and supports the [Handlebars syntax](https://handlebarsjs.com/). TNote that in order to upload files to `docs/` you must use the flag `-f`:
```bash
git add -f docs/image/my-new-image.png
```
